      SUBROUTINE UMAT(STRESS,STATEV,DDSDDE,SSE,SPD,SCD,
     1 RPL,DDSDDT,DRPLDE,DRPLDT,
     2 STRAN,DSTRAN,TIME,DTIME,TEMP,DTEMP,PREDEF,DPRED,CMNAME,
     3 NDI,NSHR,NTENS,NSTATV,PROPS,NPROPS,COORDS,DROT,PNEWDT,
     4 CELENT,DFGRD0,DFGRD1,NOEL,NPT,LAYER,KSPT,JSTEP,KINC)

      INCLUDE 'ABA_PARAM.INC'

      CHARACTER*80 CMNAME
	  
      REAL*8 STRESS(NTENS), STATEV(NSTATV), DDSDDE(NTENS, NTENS),
     1 DDSDDT(NTENS), DRPLDE(NTENS), STRAN(NTENS), DSTRAN(NTENS),
     2 TIME(2), PREDEF(1), DPRED(1), PROPS(NPROPS), COORDS(3), 
     3 DROT(3, 3), DFGRD0(3, 3), DFGRD1(3, 3), JSTEP(4)
      
! ----------------------------------------------------------------
!     UMAT FOR ISOTROPIC VON MISES YIELD CRITERION (J2 PLASTICITY)
!     LINEAR HARDENING LAW (Y = Y0 + H*EQPLAS)
!     FIRST ORDER FORWARD EULER EXPLICIT ALGORITHM
! ----------------------------------------------------------------

      REAL*8 EQPLAS, E, NU, Y0, H, LAMBDA, G, ELSTIFF(NTENS, NTENS), 
     1 SHYDRO, SMISES, Y, YIELDFN, DEQPL, FLOW(NTENS), 
     2 TERM1, TERM2, TERM3(NTENS, NTENS)

!     MATERIAL PROPERTIES INPUT

      E = PROPS(1) ! YOUNG'S MODULUS
      NU = PROPS(2) ! POISSON'S RATIO
      Y0 = PROPS(3) ! INITIAL YIELD STRESS
      H = PROPS(4) ! LINEAR HARDENING RATE
      
!     RECOVER SOLUTION DEPENDENT STATE VARIABLES FROM PREVIOUS STEP TIME INCREMENT
      EQPLAS = STATEV(1) ! EQUIVALENT PLASTIC STRAIN

!     SET UP ELASTIC STIFFNESS MATRIX 

      ELSTIFF = 0.0 ! INITIALISE THE ELASTIC STIFFNESS MATRIX TO ZERO

      LAMBDA = NU*E/((1.0 + NU)*(1.0 - 2.0*NU)) ! 1ST LAMÉ PARAMETER
      G = E/(2.0*(1.0 + NU)) ! 2ND LAMÉ PARAMETER

      IF (NDI.EQ.3) THEN ! NUMBER OF DIRECT STRESS COMPONENTS IS 3
!     THE PROBLEM IS EITHER 3D OR PLANE STRAIN
      DO I = 1, NDI
          DO J = 1, NDI
              ELSTIFF(J, I) = LAMBDA
          END DO
          ELSTIFF(I, I) = LAMBDA + 2.0*G
      END DO
      DO I = NDI+1, NTENS
          ELSTIFF(I, I) = G
      END DO

      ELSE ! NUMBER OF DIRECT STRESS COMPONENTS IS 2
!     THE PROBLEM IS PLANE STRESS
      DO I = 1, NDI 
          DO J = 1, NDI
              ELSTIFF(J, I) = NU*E/(1.0 - (NU)**2.0)
          END DO
          ELSTIFF(I, I) = E/(1.0 - (NU)**2.0)
      END DO
      DO I = NDI+1, NTENS
          ELSTIFF(I, I) = G
      END DO

      END IF

      CALL SINV(STRESS, SHYDRO, SMISES, NDI, NSHR) !UTILITY ROUTINE SINV TO CALCULATE THE STRESS INVARIANTS
      ! 1ST INVARIANT IS THE TRACE OF THE STRESS MATRIX WHICH GIVES HYDROSTATIC STRESS
      ! 2ND INVARIANT IS THE VON MISES EQUIVALENT STRESS - SQRT(3*J2)

      Y = Y0 + H*EQPLAS ! LINEAR HARDENING LAW

      YIELDFN = SMISES - Y ! YIELD FUNCTION

      IF (YIELDFN.LT.0.0) THEN
      ! THE STATE OF STRESS IS ELASTIC, HENCE ZERO PLASTIC DEFORMATION IN THIS INCREMENT
      DEQPL = 0.0

      STRESS = STRESS + MATMUL(ELSTIFF, DSTRAN)
      
      DDSDDE = ELSTIFF ! FOR ELASTIC CASE, TANGENT STIFFNESS MATRIX IS SAME AS THE ELASTIC STIFFNESS MATRIX

      ELSE
      ! THE MATERIAL HAS YIELDED, THEREFORE NON ZERO PLASTIC DEFORMATION IN THIS INCREMENT
      
      ! FLOW VECTOR FOR VON MISES
      DO I = 1, NDI ! DIRECT COMPONENTS
      FLOW(I) = 3.0*(STRESS(I) - SHYDRO)/(2.0*SMISES)
      END DO
      DO I = NDI + 1, NTENS ! SHEAR COMPONENTS
      FLOW(I) = 3.0*STRESS(I)/SMISES
      END DO

      ! CALCULATE THE INCREMENT IN EFFECTIVE PLASTIC STRAIN

      CALL INNERPROD(FLOW, MATMUL(ELSTIFF,DSTRAN), TERM1, NTENS)
      CALL INNERPROD(FLOW, MATMUL(ELSTIFF,FLOW), TERM2, NTENS)

      DEQPL = TERM1/(TERM2 + H)

      ! CALCULATE THE UPDATED STRESS
      STRESS = STRESS + MATMUL(ELSTIFF, DSTRAN - DEQPL*FLOW)

      ! EVALUATE THE MATERIAL TANGENT STIFFNESS MATRIX DDSDDE
      CALL OUTERPROD(MATMUL(ELSTIFF,FLOW), MATMUL(ELSTIFF,FLOW), 
     1 TERM3, NTENS, NTENS)

      DDSDDE = ELSTIFF - (1.0/(TERM2 + H))*TERM3

      END IF

      ! UPDATE THE EQUIVALENT PLASTIC STRAIN AND STORE IT IN THE SOLUTION DEPENDENT STATE VARIABLE
      STATEV(1) = EQPLAS + DEQPL

      RETURN
      END SUBROUTINE UMAT
! ---------------------------------------------------------------------------------------------------------------------------------

      SUBROUTINE INNERPROD(A, B, A_DOT_B, NDIM)
      ! SUBROUTINE TO CALCULATE THE INNER OR DOT PRODUCT OF TWO VECTORS EACH CONTAINING NDIM ELEMENTS
      
      INCLUDE 'ABA_PARAM.INC'

      INTEGER NDIM

      REAL*8 A(NDIM), B(NDIM), A_DOT_B
      
      IF (SIZE(A).EQ.SIZE(B)) THEN
          
          A_DOT_B = 0.0
          DO I = 1, NDIM
              A_DOT_B = A_DOT_B + A(I)*B(I)
          END DO
          
      ELSE
          
          WRITE(6,*) 'VECTOR DIMENSIONS DO NOT MATCH - INPUT ERROR'
      
      END IF

      RETURN
      END SUBROUTINE INNERPROD
! ---------------------------------------------------------------------------------------------------------------------------------
      
      SUBROUTINE OUTERPROD(A, B, A_DYAD_B, NDIM_A, NDIM_B)
      ! SUBROUTINE TO CALCULATE THE OUTER OR DYADIC PRODUCT OF TWO VECTORS CONTAINING NDIM_A AND NDIM_B ELEMENTS RESPECTIVELY
      
      INCLUDE 'ABA_PARAM.INC'

      INTEGER NDIM_A, NDIM_B
      
      REAL*8 A(NDIM_A), B(NDIM_B), A_DYAD_B(NDIM_A, NDIM_B)
          
      DO I = 1, NDIM_A
          DO J = 1, NDIM_B
              A_DYAD_B(I, J) = A(I)*B(J)
          END DO
      END DO
      
      RETURN
      END SUBROUTINE OUTERPROD
! ---------------------------------------------------------------------------------------------------------------------------------
